export const GENERATIONS = [
  {
    id: 1,
    name: "Generación I",
    region: "Kanto",
    limit: 151,
    offset: 0,
  },
  {
    id: 2,
    name: "Generación II",
    region: "Johto",
    limit: 100,
    offset: 151,
  },
  {
    id: 3,
    name: "Generación III",
    region: "Hoenn",
    limit: 135,
    offset: 251,
  },
  {
    id: 4,
    name: "Generación IV",
    region: "Sinnoh",
    limit: 107,
    offset: 386,
  },
  {
    id: 5,
    name: "Generación V",
    region: "Unova",
    limit: 156,
    offset: 493,
  },
  {
    id: 6,
    name: "Generación VI",
    region: "Kalos",
    limit: 72,
    offset: 649,
  },
  {
    id: 7,
    name: "Generación VII",
    region: "Alola",
    limit: 88,
    offset: 721,
  },
  {
    id: 8,
    name: "Generación VIII",
    region: "Galar",
    limit: 81,
    offset: 809,
  },
  {
    id: 9,
    name: "Generación IX",
    region: "Paldea",
    limit: 103,
    offset: 890,
  },
];
